//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredCorrectionsSet
    {
        public int Id { get; set; }
        public string REPORTING_ID { get; set; }
        public string REPORTS_TO_ID { get; set; }
    }
}
