//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMGMT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RTMGMTEntities : DbContext
    {
        public RTMGMTEntities()
            : base("name=RTMGMTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BottomUpProcessedRecord> BottomUpProcessedRecords { get; set; }
        public virtual DbSet<BrokenRecord> BrokenRecords { get; set; }
        public virtual DbSet<DuplicateRTRecord> DuplicateRTRecords { get; set; }
        public virtual DbSet<FixRecord> FixRecords { get; set; }
        public virtual DbSet<ReportsToRecord> ReportsToRecords { get; set; }
        public virtual DbSet<ReportsToRecordStaging> ReportsToRecordStagings { get; set; }
        public virtual DbSet<RequiredCorrectionsSet> RequiredCorrectionsSets { get; set; }
        public virtual DbSet<TopDownProcessedRecord> TopDownProcessedRecords { get; set; }
    
        public virtual int Bottom_Up_Recurse()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Bottom_Up_Recurse");
        }
    
        public virtual int DeleteAllRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAllRecords");
        }
    
        public virtual int DeleteCorrections()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCorrections");
        }
    
        public virtual int DeleteTheDuplicateRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTheDuplicateRecords");
        }
    
        public virtual int GenerateRecordFixList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateRecordFixList");
        }
    
        public virtual int GenerateReportingStructure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateReportingStructure");
        }
    
        public virtual int GetBrokenRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetBrokenRecords");
        }
    
        public virtual int GetTheDuplicateRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetTheDuplicateRecords");
        }
    
        public virtual int ImportReportsToRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ImportReportsToRecords");
        }
    
        public virtual int ProcessReportsToRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessReportsToRecords");
        }
    
        public virtual int TruncateProcessedRecordsExceptCorrections(string departmentID)
        {
            var departmentIDParameter = departmentID != null ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateProcessedRecordsExceptCorrections", departmentIDParameter);
        }
    
        public virtual int UpdateReportsToWithCorrections()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateReportsToWithCorrections");
        }
    
        public virtual int ImportsReportsToRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ImportsReportsToRecords");
        }
    
        public virtual int DeleteAllRecordsFunction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAllRecordsFunction");
        }
    }
}
